public class SalesforceDeveloper {
    
    public void myFirstCode() {
    System.debug('Asgabat');
    System.debug('Terminator');
    System.debug('Ilkbahar');
    }

    public void myFavorites(){
        Integer numara=888;
        String sehir='Ashgabat';
        System.debug(numara);
        System.debug(sehir);
        System.debug('Favori numaram-> '+numara + ' ve Favori Sehrim-> '+sehir);
    }
}